name: Update Tea Rank Badge

on:
  # Run daily at 2:20 AM UTC
  schedule:
    - cron: '20 2 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:
  
  # Run on push to main for initial setup
  push:
    branches: [ main ]
    paths:
      - 'README.md'

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update teaRank Badge
        uses: cryptoflops/tea-rank-badge@v1
        with:
          project_name: 'curl'  # Tracking the curl project as a demo
          svg_path: '.github/tea-rank-badge.svg'
          readme_path: 'README.md'
          label: 'teaRank'
          style: 'flat-square'
          precision: '4'  # Show 4 decimal places for demonstration
          insert: 'true'
          commit_message: 'chore: update teaRank badge for curl [skip ci]'

      - name: Display Results
        if: success()
        run: |
          echo "✅ Badge update complete!"
          echo "Check the README for the updated badge"
